from .coordenates_request_view import CoordinatesList
from .coordenates_request_view import CoordinatesDetail
from .coordenates_service_view import CoordinatesList
from .coordenates_service_view import CoordinatesDetail
from .request_view import RequestDetail
from .request_view import RequestList
from .user_view import UserDetail
from .user_view import UserList
from .service_view import ServiceList
from .service_view import ServiceDetail